name: update

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Delete .git
      run: |
        pwd
        ls -la
        rm -rf ./.git ./github
        cd ..
        pwd
        ls -la
    - uses: actions/checkout@master
      with:
        repository: Itsmecomeon/Itsmecomeon
    - name: Update content
      run: |
        pwd
        ls -la
        cd ..
        mv ./content/* ./Itsmecomeon
        pwd
        ls -la
        cd ./Itsmecomeon
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "Add changes" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
